// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DarkToggle: typeof import('./src/components/DarkToggle.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MessageToggle: typeof import('./src/components/MessageToggle.vue')['default']
  }
}

export { }
