// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DarkToggle: typeof import('./src/components/DarkToggle.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GithubButton: typeof import('./src/components/GithubButton.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MessageToggle: typeof import('./src/components/MessageToggle.vue')['default']
    MoonIcon: typeof import('./src/components/MoonIcon.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SunIcon: typeof import('./src/components/SunIcon.vue')['default']
  }
}

export { }
